[package]
name = "httpd"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { version = " 1.29.1", features = ["full"] }
chrono = "0.4.26"
flate2 = "1.0.26"
clap = { version = "4.3.19", features = ["derive"] }
toml = "0.7.6"
once_cell = "1.18.0"
serde = { version = "1.0.177", features = ["derive"] }
tokio-rustls = "0.23.4"
rustls-pemfile = "1.0.3"
bytes = "1.4.0"
pin-project = "1.1.2"
async-trait = "0.1.72"
brotli2 = "0.3.2"
