[package]
name = "httpd"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = " 1.36.0", features = ["full"] }
bytebuffer = "2.2.0"
chrono = "0.4.34"
flate2 = "1.0.28"
clap = { version = "4.5.1", features = ["derive"] }
toml = "0.8.10"
serde = { version = "1.0.197", features = ["derive"] }
tokio-rustls = "0.25.0"
rustls-pemfile = "2.1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
log = "0.4.17"
# regex = "1.10.3"

