[package]
name = "httpd"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = " 1.24.1", features = ["full"] }
async-trait = "0.1.63"
bytebuffer = "2.1.0"
