[package]
name = "httpd"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = " 1.24.1", features = ["full"] }
async-trait = "0.1.63"
bytebuffer = "2.1.0"
chrono = "0.4.23"
flate2 = "1.0.25"
clap = { version = "4.1.4", features = ["derive"] }
toml = "0.6.0"
once_cell = "1.17.0"
serde = { version="1.0.152", features= ["derive"] }
tokio-rustls = "0.23.4"
rustls-pemfile = "1.0.2"
