[package]
name = "httpd"
version = "0.0.1"
edition = "2021"

[profile.release]
opt-level = 3

[workspace]
members = ["logging"]

[features]

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
tokio = { version = " 1.36.0", features = ["full"] }
bytebuffer = "2.2.0"
glob = { version = "0.3.1" }
logging = { path = "./logging" }

# compression
flate2 = "1.0.28"
brotli = "3.4.0"

# config
toml = { version = "0.8.10" }
serde = { version = "1.0.197", features = ["derive"] }

# ssl
tokio-rustls = { version = "0.25.0" }
rustls-pemfile = { version = "2.1.0" }

# loggging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json"] }
tracing-appender = "0.2.3"
async-trait = "0.1.77"
tracing-futures = { version = "0.2.5", features = ["tokio"] }
