version: '3.1'

services:
  RustAlpine:
    container_name: rustalpine
    image: rust:1.67.1-alpine3.17
    volumes:
      - ${CODES_PATH}:/usr/local/codes
    command: "sleep 86400s"
    ports:
      - "0.0.0.0:18080:8080"
    restart: on-failure