name: Build on different platforms

on:
  release:
    branches: [master]
    types: [created]

jobs:
  release-on-ubuntu:
    name: Release on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
  
  # release-on-windows:
  #   name: Release on Windows
  #   runs-on: windows-latest
  #   steps:          
  #     - uses: actions/checkout@v4
  #     - uses: actions-rust-lang/setup-rust-toolchain@v1

  # reslease-on-macos:
  #   name: Release on macOS
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions-rust-lang/setup-rust-toolchain@v1