name: Build on different platforms

on:
  release:
    branches: [master]
    types: [created]

jobs:
  release-on-ubuntu:
    name: Release on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: httpd.rs
          path: target/release/httpd
  
  # release-on-windows:
  #   name: Release on Windows
  #   runs-on: windows-latest
  #   steps:          
  #     - uses: actions/checkout@v4
  #     - uses: actions-rust-lang/setup-rust-toolchain@v1

  # reslease-on-macos:
  #   name: Release on macOS
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions-rust-lang/setup-rust-toolchain@v1